spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.10:27117/fileStore
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  kafka:
    consumer:
      group-id: common-group
      auto-offset-reset: earliest
    bootstrap-servers: 192.168.0.10:29092
reportingServiceHost: localhost
reportingServicePort: 8228